export const messages = {
  us: {
    snah_id: "Please provide SNAH_ID",
    full_name: "Please provide Full Name",
    email_required: "Email is required",
    email_invalid: "Invalid email",
    phone_required: "Phone is required",
    tel_phone: "Please provide Tel_phone",
    establishedDate_required: "Establish Date is required",
    establishedDate_invalid: "Invalid date format",
    ein: "Please provide EIN",
    npl: "Please provide NPL",
    createdDate_required: "Created Date is required",
    createdDate_invalid: "Invalid date format",
    registrationId: "Please provide registrationID",
    user_name: "Please provide User Name",
    admin_rep_name: "Please provide Admin Rep Name",
    admin_rep_title: "Please provide Admin Rep Title",
    faxnumber: "Please provide FAX Number",
    tax: "Please provide Tax",
    about: "Please provide about",
    address: "Please provide address",
    streetAddress: "Please provide street address",
    city: "Please provide city",
    state: "Please provide state",
    zipcode: "Please provide zipcode",
    county: "Please provide country",
    categoryNameRequired: "Please provide Category Name",
    categoryNameMinLength: "Category Name must be at least 2 characters",
    categoryNameMaxLength: "Category Name must be at most 50 characters",
    phoneNumberRequired: "Please provide Phone Number",
    phoneNumberMinLength: "Phone Number must be at least 10 characters",
    phoneNumberMaxLength: "Phone Number must be at most 15 characters",
    staffMember: {
      createUpdate: {
        firstName: "Please provide First Name",
        lastName: "Please provide Last Name",
        email: "Please provide Email",
        mobile: "Please provide Mobile Number",
        dob: "Please provide Date of Birth",
        joiningDate: "Please provide Joining Date",
        pin: "Please provide PIN",
        gender: "Please select Gender",
        institutionName: "Please provide Institution Name",
        departmentName: "Please provide Department Name",
        degree: "Please provide Degree",
        courseDuration: "Please provide Course Duration",
        organizationName: "Please provide Organization Name",
        position: "Please provide Position",
        workExperienceDuration: "Please provide Work Experience Duration",
        country: "Please provide Country",
        city: "Please provide City",
        state: "Please provide State",
        pinCode: "Please provide Pin Code",
        about: "Please provide About",
      },
      profilePin: {
        newPin: "Please provide New PIN",
        confirmNewPin: "Please provide Confirm New PIN",
      }
    },
    appointment: {
      create: {
        searchPatient: "Please provide Search Patient",
        patient: "Please provide Patient",
        physician: "Please provide Physician",
        appointmentType: "Please provide Appointment Type",
        appointmentDate: "Please provide Appointment Date",
        medicalIssue: "Please provide Medical Issue",
        appointmentReason: "Please provide Appointment Reason",
        symptoms: "Please provide Symptoms",
      },
      service: {
        serviceName: "Please provide Service Name",
        serviceFee: "Please provide Service Fee",
        totalServiceFee: "Please provide Total Service Fee",
        taxPercentage: "Please provide Tax Percentage",
        totalEstimatedCharge: "Please provide Total Estimated Charge",
        userPay: "Please provide User Pay",
        insurancePay: "Please provide Insurance Pay",
        insuranceCompany: "Please provide Insurance Company",
      },
      addPaperPrescription: {
        pharmacyZip: "Please provide Pharmacy Zip",
        pharmacy: "Please provide Pharmacy Name",
        ncpdp: "Please provide NCPDP",
        prescriptionType: "Please provide Prescription Type",
        physicianDea: "Please provide Physician DEA",
        file: "Please upload a file",
        prescriptionNotes: "Please provide Prescription Notes",
        additionalNotes: "Please provide Additional Notes",
        bloodPressureHigh: "Please provide High Blood Pressure value",
        bloodPressureLow: "Please provide Low Blood Pressure value",
        oxygen: "Please provide Oxygen level",
        ecg: "Please provide ECG information",
        healthInformation: "Please provide Health Information",
        treatment: "Please provide Treatment details",
        otherCare: "Please provide Other Care details",
      },
      cancelReject: {
        reason: "Please provide a reason for cancellation"
      },
      outPatient: {
        firstName: "Please provide First Name",
        lastName: "Please provide Last Name",
        dateAdmitted: "Please provide Date Admitted",
        reasonForAppointment: "Please provide Reason for Appointment",
        diagnosis: "Please provide Diagnosis",
        treatmentTaken: "Please provide Treatment Taken",
        timeOfTreatment: "Please provide Time of Treatment",
        wasTreatmentRequestedByPhysician: "Please provide Was Treatment Requested By Physician",
        treatmentNotes: "Please provide Treatment Notes",
        isFutureTreatmentNeeded: "Please provide Is Future Treatment Needed",
        futureTreatmentDate: "Please provide Future Treatment Date",
        futureTreatmentNote: "Please provide Future Treatment Note",
        patientPrescribedMedication: "Please provide Patient Prescribed Medication",
        attendingMedicalProvider: "Please provide Attending Medical Provider"
      }
    },
    medicalProvider: {
      physician: {
        firstName: "Please provide First Name",
        lastName: "Please provide Last Name",
        email: "Please provide Email",
        phone: "Please provide Phone Number",
        licenseNumber: "Please provide Medical Provider’s License Number",
        position: "Please provide Position",
        npiNumber: "Please provide NPI Number",
        specialty: "Please select Specialty",
        department: "Please select Department",
        experience: "Please provide Years of Experience",
        dob: "Please provide Date of Birth",
        language: "Please select Language Spoken",
        insurance: "Please select Insurance Accepted",
        about: "Please provide About Yourself",
        country: "Please provide Country",
        street: "Please provide Street Address",
        city: "Please provide City",
        state: "Please provide State",
        postalCode: "Please provide Postal Code",
        institutionName: "Please provide Institution Name",
        boardCertifications: "Please provide Board Certifications",
        degree: "Please provide Degree",
        courseDuration: "Please provide Course Duration",
        organizationName: "Please provide Organization Name",
        departmentName: "Please provide Department Name",
        workExperienceDuration: "Please provide Work Experience Duration"
      }
    },
    profile: {
      kycDocument: {
        documentType: "Please provide Document Type",
        documentNumber: "Please provide Document Number",
        document: "Please upload Document",
      },
      insuranceCovered: {
        selectInsurance: "Please select Insurance",
        startDate: "Please provide Start Date",
        providerId: "Please provide Provider ID",
        endYear: "Please provide End Year",
      },
      certification: {
        date: "Please provide Certification Date",
        document: "Please upload Certification Document",
      },
      accountLinked: {
        accountHolderName: "Please provide Account Holder Name",
        accountNumber: "Please provide Account Number",
        bankName: "Please provide Bank Name",
        branchName: "Please provide Branch Name",
        routingNumber: "Please provide Routing Number",
        accountType: "Please provide Account Type",
        accountOwnership: "Please provide Account Ownership",
        street: "Please provide Street",
        city: "Please provide City",
        state: "Please provide State",
        zipCode: "Please provide Zip Code",
      },
      profile: {
        name: "Please provide Name",
        registrationId: "Please provide Registration ID",
        phone: "Please provide Phone",
        telPhone: "Please provide Tel Phone",
        createUserName: "Please provide User Name",
        adminRepFullName: "Please provide Admin Rep Full Name",
        adminRepTitle: "Please provide Admin Rep Title",
        faxNumber: "Please provide Fax Number",
        tax: "Please provide Tax",
        npi: "Please provide NPI",
        ein: "Please provide EIN",
        establishedDate: "Please provide Established Date",
        taxonomy: "Please provide Taxonomy",
        naicsCode: "Please provide NAICS Code",
        about: "Please provide About",
        address: "Please provide Address",
        streetAddress: "Please provide Street Address",
        city: "Please provide City",
        state: "Please provide State",
        zipCode: "Please provide Zip Code",
        country: "Please provide Country",
      }
    },
    report: {
      appointmentId: "Please provide Appointment ID",
      planName: "Please provide Plan Name",
      description: "Please provide Description",
    },
    manageMember: {
      member: {
        firstName: "Please provide First Name",
        lastName: "Please provide Last Name",
        personName: "Please provide Person Name",
        authorizedBy: "Please provide Authorized By",
        dateTime: "Please provide Date & Time",
        amount: "Please provide Amount",
        bankAccount: "Please provide Bank Account",
      }
    },
    manageClaim: {
      facility: {
        claim: {
          claimType: "Please provide Claim Type",
          appointmentDate: "Please provide Appointment Date",
          appointmentId: "Please provide Appointment ID",
          patientInsurance: "Please provide Patient Insurance",
          currentIllnessDate: "Please provide Current Illness Date",
          currentIllnessQual: "Please provide Current Illness Qual",
          otherDate: "Please provide Other Date",
          otherDateQual: "Please provide Other Date Qual",
          unableToWork: "Please provide Unable To Work",
          hospitalization: "Please provide Hospitalization",
          referringProvider: "Please provide Referring Provider",
          additionalClaimInfo: "Please provide Additional Claim Info",
          outsideLab: "Please provide Outside Lab",
          outsideLabCharges: "Please provide Outside Lab Charges",
          diagnosis1: "Please provide Diagnosis 1",
          diagnosis2: "Please provide Diagnosis 2",
          diagnosis3: "Please provide Diagnosis 3",
          icdForCpt: "Please provide ICD for CPT",
          cpt: "Please provide CPT",
          resubmissionCode: "Please provide Resubmission Code",
          resubmissionOriginalRef: "Please provide Resubmission Original Ref",
          priorAuthNumber: "Please provide Prior Auth Number",
          services: "Please provide Services",
          documents: "Please provide Documents",
          taxIdNumber: "Please provide Tax ID Number",
          taxIdSSN: "Please provide Tax ID SSN",
          taxIdEIN: "Please provide Tax ID EIN",
          patientAccountNo: "Please provide Patient Account No",
          acceptAssignment: "Please provide Accept Assignment",
          totalCharge: "Please provide Total Charge",
          amountPaid: "Please provide Amount Paid",
          nuccReserved: "Please provide NUCC Reserved"
        },
        document: {
          typeOfFile: "Please provide type of file",
          document: "Please provide document"
        },
        service: {
          dateOfService: "Please provide Date of Service",
          placeOfService: "Please provide Place of Service",
          emg: "Please provide EMG",
          cptNumber: "Please provide CPT Number",
          cptHcpcs: "Please provide CPT HCPCS",
          modifier: "Please provide Modifier",
          diagnosisPointer: "Please provide Diagnosis Pointer",
          charges: "Please provide Charges",
          daysOrUnits: "Please provide Days or Units",
          epsdtFamilyPlan: "Please provide EPSDT Family Plan",
          idQual: "Please provide ID Qual",
          referringProviderId: "Please provide Referring Provider ID"
        },
        allergy: {
          dateOfAllergy: "Please provide Date of Allergy",
          numberOfVialsAllergy: "Please provide Number of Vials Allergy",
          numberOfTreatmentsAllergy: "Please provide Number of Treatments Allergy",
          daysSupplyAllergy: "Please provide Days Supply Allergy",
          vialContainsAllergy: "Please provide Vial Contains Allergy",
          administeredByAllergy: "Please provide Administered By Allergy",
          directionsAllergy: "Please provide Directions Allergy",
          ingredientsAllergy: "Please provide Ingredients Allergy",
          chargePerTreatmentAllergy: "Please provide Charge Per Treatment Allergy",
          chargeForPreparationAllergy: "Please provide Charge For Preparation Allergy",
          totalChargeAllergy: "Please provide Total Charge Allergy"
        },
        send: {
          subject: "Please provide Subject",
          content: "Please provide Content"
        }
      },
      pharmacy: {
        claim: {
          appointmentId: "Please provide Appointment ID",
          patientInsurance: "Please provide Patient Insurance",
          additionalComments: "Please provide Additional Comments",
          onSitePharmacy: "Please provide On-Site Pharmacy",
          pharmacistSignature: "Please provide Pharmacist Signature",
          filingReason: "Please provide Filing Reason",
          otherProvideReason: "Please provide Other Provide Reason",
          medicationOutsideUS: "Please provide Medication Outside US",
          purchasedOutsideCountry: "Please provide Purchased Outside Country",
          purchasedOutsideCurrency: "Please provide Purchased Outside Currency",
          anyMedicinesTaken: "Please provide Any Medicines Taken",
          medicineCoveredByOtherInsurance: "Please provide Medicine Covered By Other Insurance",
          otherCoverage: "Please provide Other Coverage",
          nameOfInsuranceCompany: "Please provide Name Of Insurance Company",
          insuranceId: "Please provide Insurance ID",
          memberSignature: "Please provide Member Signature",
          numberOfPrescriptions: "Please provide Number Of Prescriptions",
          prescribingPhysicianNpiNumber: "Please provide Prescribing Physician NPI Number",
          prescribingPhysicianPhoneNumber: "Please provide Prescribing Physician Phone Number",
          prescribingPhysicianName: "Please provide Prescribing Physician Name",
          prescribingPhysicianAddress: "Please provide Prescribing Physician Address",
          prescribingPhysicianCityStateZip: "Please provide Prescribing Physician City State Zip",
          prescribingPhysicianAdditionalComments: "Please provide Prescribing Physician Additional Comments",
          grandTotal: "Please provide Grand Total",
          otherInformation: "Please provide Other Information"
        },
        send: {
          subject: "Please provide Subject",
          content: "Please provide Content"
        },
        allergy: {
          dateOfAllergy: "Please provide Date of Allergy",
          numberOfVialsAllergy: "Please provide Number of Vials Allergy",
          numberOfTreatmentsAllergy: "Please provide Number of Treatments Allergy",
          daysSupplyAllergy: "Please provide Days Supply Allergy",
          vialContainsAllergy: "Please provide Vial Contains Allergy",
          administeredByAllergy: "Please provide Administered By Allergy",
          directionsAllergy: "Please provide Directions Allergy",
          ingredientsAllergy: "Please provide Ingredients Allergy",
          chargePerTreatmentAllergy: "Please provide Charge Per Treatment Allergy",
          chargeForPreparationAllergy: "Please provide Charge For Preparation Allergy",
          totalChargeAllergy: "Please provide Total Charge Allergy"
        }
      },
      settled: {
        missingReject: {
          reason: "Please provide a reason"
        },
        payClaim: {
          bankAccount: "Please provide Bank Account",
          payingAmount: "Please provide Paying Amount"
        },
        return: {
          reason: "Please provide a reason",
        }
      }
    },
    managePrescription: {
      prescription: {
        ndcAdd: {
          ndcNumber: "Please provide NDC Number",
          selectedNDC: "Please provide Selected NDC"
        },
        invoice: {
          claimType: "Please provide Claim Type",
          appointmentId: "Please provide Appointment ID",
          patientInsurance: "Please provide Patient Insurance",
          invoiceDate: "Please provide Invoice Date",
          medicationStartDate: "Please provide Medication Start Date",
          appointmentDate: "Please provide Appointment Date",
          grandTotal: "Please provide Grand Total",
          coPay: "Please provide Co-Pay",
          patientPay: "Please provide Patient Pay",
          insurancePay: "Please provide Insurance Pay",
          otherInformation: "Please provide Other Information",
          medicineType: "Please provide Medicine Type",
          frequency: "Please provide Frequency",
          foodRequirementType: "Please provide Food Requirement Type",
          durationType: "Please provide Duration Type",
          durationNumber: "Please provide Duration Number",
          startDate: "Please provide Start Date",
          dosage: "Please provide Dosage",
          isRefill: "Please provide Is Refill",
          instructions: "Please provide Instructions",
          notes: "Please provide Notes",
          price: "Please provide Price",
          quantity: "Please provide Quantity",
          tax: "Please provide Tax",
          total: "Please provide Total",
        }
      }
    }
  },
  ar: {
    snah_id: "يرجى تقديم SNAH_ID",
    full_name: "يرجى تقديم الاسم الكامل",
    email_required: "البريد الإلكتروني مطلوب",
    email_invalid: "البريد الإلكتروني غير صالح",
    phone_required: "رقم الهاتف مطلوب",
    tel_phone: "يرجى تقديم رقم الهاتف",
    establishedDate_required: "تاريخ التأسيس مطلوب",
    establishedDate_invalid: "تنسيق تاريخ غير صالح",
    ein: "يرجى تقديم EIN",
    npl: "يرجى تقديم NPL",
    createdDate_required: "تاريخ الإنشاء مطلوب",
    createdDate_invalid: "تنسيق تاريخ غير صالح",
    registrationId: "يرجى تقديم معرف التسجيل",
    user_name: "يرجى تقديم اسم المستخدم",
    admin_rep_name: "يرجى تقديم اسم ممثل الإدارة",
    admin_rep_title: "يرجى تقديم لقب ممثل الإدارة",
    faxnumber: "يرجى تقديم رقم الفاكس",
    tax: "يرجى تقديم الضريبة",
    about: "يرجى تقديم معلومات",
    address: "يرجى تقديم العنوان",
    streetAddress: "يرجى تقديم عنوان الشارع",
    city: "يرجى تقديم المدينة",
    state: "يرجى تقديم الولاية",
    zipcode: "يرجى تقديم الرمز البريدي",
    county: "يرجى تقديم البلد",
    name: "يرجى تقديم اسم الفئة",
    phone: "يرجى تقديم رقم الهاتف",
    categoryNameRequired: "يرجى تقديم اسم الفئة",
    categoryNameMinLength: "يجب أن يتكون اسم الفئة من 2 حرف على الأقل",
    categoryNameMaxLength: "يجب أن يتكون اسم الفئة من 50 حرفًا كحد أقصى",
    phoneNumberRequired: "يرجى تقديم رقم الهاتف",
    phoneNumberMinLength: "يجب أن يتكون رقم الهاتف من 10 أحرف على الأقل",
    phoneNumberMaxLength: "يجب أن يتكون رقم الهاتف من 15 حرفًا كحد أقصى",
    staffMember: {
      createUpdate: {
        firstName: "يرجى تقديم الاسم الأول",
        lastName: "يرجى تقديم اسم العائلة",
        email: "يرجى تقديم البريد الإلكتروني",
        mobile: "يرجى تقديم رقم الجوال",
        dob: "يرجى تقديم تاريخ الميلاد",
        joiningDate: "يرجى تقديم تاريخ الانضمام",
        pin: "يرجى تقديم الرقم السري",
        gender: "يرجى تحديد الجنس",
        institutionName: "يرجى تقديم اسم المؤسسة",
        departmentName: "يرجى تقديم اسم القسم",
        degree: "يرجى تقديم الدرجة العلمية",
        courseDuration: "يرجى تقديم مدة الدورة",
        organizationName: "يرجى تقديم اسم المنظمة",
        position: "يرجى تقديم المنصب",
        workExperienceDuration: "يرجى تقديم مدة الخبرة العملية",
        country: "يرجى تقديم البلد",
        city: "يرجى تقديم المدينة",
        state: "يرجى تقديم الولاية",
        pinCode: "يرجى تقديم الرمز البريدي",
        about: "يرجى تقديم نبذة عنك",
      },
      profilePin: {
        newPin: "يرجى تقديم الرقم السري الجديد",
        confirmNewPin: "يرجى تقديم تأكيد الرقم السري الجديد",
      }
    },
    appointment: {
      create: {
        searchPatient: "أقصى حد لتوفير بحث المريض",
        patient: "يرجى تقديم المريض",
        physician: "يرجى تقديم الطبيب",
        appointmentType: "يرجى تقديم نوع الموعد",
        appointmentDate: "يرجى تقديم تاريخ الموعد",
        medicalIssue: "يرجى تقديم المشكلة الطبية",
        appointmentReason: "يرجى تقديم سبب الموعد",
        symptoms: "يرجى تقديم الأعراض",
      },
      service: {
        serviceName: "يرجى تقديم اسم الخدمة",
        serviceFee: "يرجى تقديم رسوم الخدمة",
        totalServiceFee: "يرجى تقديم إجمالي رسوم الخدمة",
        taxPercentage: "يرجى تقديم نسبة الضريبة",
        totalEstimatedCharge: "يرجى تقديم إجمالي التكلفة المقدرة",
        userPay: "يرجى تقديم ما سيدفعه المستخدم",
        insurancePay: "يرجى تقديم ما ستدفعه شركة التأمين",
        insuranceCompany: "يرجى تقديم شركة التأمين",
      },
      addPaperPrescription: {
        pharmacyZip: "يرجى تقديم الرمز البريدي للصيدلية",
        pharmacy: "يرجى تقديم اسم الصيدلية",
        ncpdp: "يرجى تقديم رقم NCPDP",
        prescriptionType: "يرجى تقديم نوع الوصفة الطبية",
        physicianDea: "يرجى تقديم رقم DEA للطبيب",
        file: "يرجى تحميل ملف",
        prescriptionNotes: "يرجى تقديم ملاحظات الوصفة الطبية",
        additionalNotes: "يرجى تقديم ملاحظات إضافية",
        bloodPressureHigh: "يرجى تقديم قيمة ضغط الدم المرتفع",
        bloodPressureLow: "يرجى تقديم قيمة ضغط الدم المنخفض",
        oxygen: "يرجى تقديم مستوى الأكسجين",
        ecg: "يرجى تقديم معلومات تخطيط القلب (ECG)",
        healthInformation: "يرجى تقديم المعلومات الصحية",
        treatment: "يرجى تقديم تفاصيل العلاج",
        otherCare: "يرجى تقديم تفاصيل الرعاية الأخرى",
      },
      cancelReject: {
        reason: "يرجى تقديم سبب الإلغاء"
      },
      outPatient: {
        firstName: "يرجى تقديم الاسم الأول",
        lastName: "يرجى تقديم اسم العائلة",
        dateAdmitted: "يرجى تقديم تاريخ القبول",
        reasonForAppointment: "يرجى تقديم سبب الموعد",
        diagnosis: "يرجى تقديم التشخيص",
        treatmentTaken: "يرجى تقديم العلاج المتخذ",
        timeOfTreatment: "يرجى تقديم وقت العلاج",
        wasTreatmentRequestedByPhysician: "يرجى تقديم ما إذا كان العلاج مطلوبًا من قبل الطبيب",
        treatmentNotes: "يرجى تقديم ملاحظات العلاج",
        isFutureTreatmentNeeded: "يرجى تقديم ما إذا كان العلاج المستقبلي مطلوبًا",
        futureTreatmentDate: "يرجى تقديم تاريخ العلاج المستقبلي",
        futureTreatmentNote: "يرجى تقديم ملاحظات العلاج المستقبلي",
        patientPrescribedMedication: "يرجى تقديم الأدوية الموصوفة للمريض",
        attendingMedicalProvider: "يرجى تقديم مزود الرعاية الطبية المعالج"
      }
    },
    medicalProvider: {
      physician: {
        firstName: "يرجى تقديم الاسم الأول",
        lastName: "يرجى تقديم اسم العائلة",
        email: "يرجى تقديم البريد الإلكتروني",
        phone: "يرجى تقديم رقم الهاتف",
        licenseNumber: "يرجى تقديم رقم ترخيص مزود الرعاية الطبية",
        position: "يرجى تقديم المسمى الوظيفي",
        npiNumber: "يرجى تقديم رقم NPI",
        specialty: "يرجى اختيار التخصص",
        department: "يرجى اختيار القسم",
        experience: "يرجى تقديم سنوات الخبرة",
        dob: "يرجى تقديم تاريخ الميلاد",
        language: "يرجى اختيار اللغة المنطوقة",
        insurance: "يرجى اختيار التأمين المقبول",
        about: "يرجى تقديم معلومات عن نفسك",
        country: "يرجى تقديم الدولة",
        street: "يرجى تقديم عنوان الشارع",
        city: "يرجى تقديم المدينة",
        state: "يرجى تقديم الولاية",
        postalCode: "يرجى تقديم الرمز البريدي",
        institutionName: "يرجى تقديم اسم المؤسسة",
        boardCertifications: "يرجى تقديم الشهادات المهنية",
        degree: "يرجى تقديم الدرجة العلمية",
        courseDuration: "يرجى تقديم مدة الدورة",
        organizationName: "يرجى تقديم اسم المؤسسة",
        departmentName: "يرجى تقديم اسم القسم",
        workExperienceDuration: "يرجى تقديم مدة الخبرة العملية"
      }
    },
    profile: {
      kycDocument: {
        documentType: "يرجى تقديم نوع الوثيقة",
        documentNumber: "يرجى تقديم رقم الوثيقة",
        document: "يرجى تحميل الوثيقة",
      },
      insuranceCovered: {
        selectInsurance: "يرجى اختيار التأمين",
        startDate: "يرجى تقديم تاريخ البدء",
        providerId: "يرجى تقديم معرف المزود",
        endYear: "يرجى تقديم تاريخ الانتهاء",
      },
      certification: {
        date: "يرجى تقديم تاريخ الشهادة",
        document: "يرجى تحميل وثيقة الشهادة",
      },
      accountLinked: {
        accountHolderName: "يرجى تقديم اسم صاحب الحساب",
        accountNumber: "يرجى تقديم رقم الحساب",
        bankName: "يرجى تقديم اسم البنك",
        branchName: "يرجى تقديم اسم الفرع",
        routingNumber: "يرجى تقديم رقم التوجيه",
        accountType: "يرجى تقديم نوع الحساب",
        accountOwnership: "يرجى تقديم ملكية الحساب",
        street: "يرجى تقديم الشارع",
        city: "يرجى تقديم المدينة",
        state: "يرجى تقديم الولاية",
        zipCode: "يرجى تقديم الرمز البريدي",
      },
      profile: {
        name: "يرجى تقديم الاسم",
        registrationId: "يرجى تقديم معرف التسجيل",
        phone: "يرجى تقديم رقم الهاتف",
        telPhone: "يرجى تقديم رقم الهاتف الثابت",
        createUserName: "يرجى تقديم اسم المستخدم",
        adminRepFullName: "يرجى تقديم الاسم الكامل لممثل الإدارة",
        adminRepTitle: "يرجى تقديم لقب ممثل الإدارة",
        faxNumber: "يرجى تقديم رقم الفاكس",
        tax: "يرجى تقديم الضريبة",
        npi: "يرجى تقديم رقم NPI",
        ein: "يرجى تقديم رقم EIN",
        establishedDate: "يرجى تقديم تاريخ التأسيس",
        taxonomy: "يرجى تقديم التصنيف",
        naicsCode: "يرجى تقديم رمز NAICS",
        about: "يرجى تقديم نبذة عنك",
        address: "يرجى تقديم العنوان",
        streetAddress: "يرجى تقديم عنوان الشارع",
        city: "يرجى تقديم المدينة",
        state: "يرجى تقديم الولاية",
        zipCode: "يرجى تقديم الرمز البريدي",
        country: "يرجى تقديم البلد",
      }
    },
    report: {
      appointmentId: "يرجى تقديم معرف الموعد",
      planName: "يرجى تقديم اسم الخطة",
      description: "يرجى تقديم الوصف",
    },
    manageMember: {
      member: {
        firstName: "يرجى تقديم الاسم الأول",
        lastName: "يرجى تقديم الاسم الأخير",
        personName: "يرجى تقديم اسم الشخص",
        authorizedBy: "يرجى تقديم اسم المفوض",
        dateTime: "يرجى تقديم التاريخ والوقت",
        amount: "يرجى تقديم المبلغ",
        bankAccount: "يرجى تقديم رقم الحساب",
      }
    },
    manageClaim: {
      facility: {
        claim: {
          claimType: "يرجى تقديم نوع المطالبة",
          appointmentDate: "يرجى تقديم تاريخ الموعد",
          appointmentId: "يرجى تقديم معرف الموعد",
          patientInsurance: "يرجى تقديم تأمين المريض",
          currentIllnessDate: "يرجى تقديم تاريخ المرض الحالي",
          currentIllnessQual: "يرجى تقديم وصف المرض الحالي",
          otherDate: "يرجى تقديم تاريخ آخر",
          otherDateQual: "يرجى تقديم وصف آخر",
          unableToWork: "يرجى تقديم غير قادر على العمل",
          hospitalization: "يرجى تقديم الاستشفاء",
          referringProvider: "يرجى تقديم مزود الإحالة",
          additionalClaimInfo: "يرجى تقديم معلومات المطالبة الإضافية",
          outsideLab: "يرجى تقديم مختبر خارجي",
          outsideLabCharges: "يرجى تقديم رسوم المختبر الخارجي",
          diagnosis1: "يرجى تقديم التشخيص 1",
          diagnosis2: "يرجى تقديم التشخيص 2",
          diagnosis3: "يرجى تقديم التشخيص 3",
          icdForCpt: "يرجى تقديم رمز التشخيص (ICD) للإجراء (CPT)",
          cpt: "يرجى تقديم رمز الإجراء (CPT)",
          resubmissionCode: "يرجى تقديم رمز إعادة التقديم",
          resubmissionOriginalRef: "يرجى تقديم المرجع الأصلي لإعادة التقديم",
          priorAuthNumber: "يرجى تقديم رقم التفويض المسبق",
          services: "يرجى تقديم الخدمات",
          documents: "يرجى تقديم المستندات",
          taxIdNumber: "يرجى تقديم رقم التعريف الضريبي",
          taxIdSSN: "يرجى تقديم رقم الضمان الاجتماعي",
          taxIdEIN: "يرجى تقديم رقم تعريف صاحب العمل",
          patientAccountNo: "يرجى تقديم رقم حساب المريض",
          acceptAssignment: "يرجى تقديم قبول التعيين",
          totalCharge: "يرجى تقديم إجمالي الرسوم",
          amountPaid: "يرجى تقديم المبلغ المدفوع",
          nuccReserved: "يرجى تقديم الحقل المحجوز (NUCC)"
        },
        document: {
          typeOfFile: "يرجى تقديم نوع الملف",
          document: "يرجى تقديم الوثيقة"
        },
        service: {
          dateOfService: "يرجى تقديم تاريخ الخدمة",
          placeOfService: "يرجى تقديم مكان الخدمة",
          emg: "يرجى تقديم حالة الطوارئ (EMG)",
          cptNumber: "يرجى تقديم رقم CPT",
          cptHcpcs: "يرجى تقديم رمز CPT/HCPCS",
          modifier: "يرجى تقديم المُعدِّل",
          diagnosisPointer: "يرجى تقديم مؤشر التشخيص",
          charges: "يرجى تقديم الرسوم",
          daysOrUnits: "يرجى تقديم الأيام أو الوحدات",
          epsdtFamilyPlan: "يرجى تقديم خطة الأسرة (EPSDT)",
          idQual: "يرجى تقديم نوعية المعرف",
          referringProviderId: "يرجى تقديم معرف مزود الإحالة"
        },
        allergy: {
          dateOfAllergy: "يرجى تقديم تاريخ الحساسية",
          numberOfVialsAllergy: "يرجى تقديم عدد قوارير الحساسية",
          numberOfTreatmentsAllergy: "يرجى تقديم عدد علاجات الحساسية",
          daysSupplyAllergy: "يرجى تقديم أيام تزويد الحساسية",
          vialContainsAllergy: "يرجى تقديم محتوى القارورة للحساسية",
          administeredByAllergy: "يرجى تقديم اسم المسؤول عن إعطاء الحساسية",
          directionsAllergy: "يرجى تقديم تعليمات الحساسية",
          ingredientsAllergy: "يرجى تقديم مكونات الحساسية",
          chargePerTreatmentAllergy: "يرجى تقديم تكلفة كل علاج للحساسية",
          chargeForPreparationAllergy: "يرجى تقديم تكلفة التحضير للحساسية",
          totalChargeAllergy: "يرجى تقديم إجمالي تكلفة الحساسية"
        },
        send: {
          subject: "يرجى تقديم الموضوع",
          content: "يرجى تقديم المحتوى"
        }
      },
      pharmacy: {
        claim: {
          appointmentId: "يرجى تقديم معرف الموعد",
          patientInsurance: "يرجى تقديم تأمين المريض",
          additionalComments: "يرجى تقديم التعليقات الإضافية",
          onSitePharmacy: "يرجى تقديم صيدلية الموقع",
          pharmacistSignature: "يرجى تقديم توقيع الصيدلي",
          filingReason: "يرجى تقديم سبب التقديم",
          otherProvideReason: "يرجى تقديم سبب آخر للتقديم",
          medicationOutsideUS: "يرجى تقديم معلومات الدواء خارج الولايات المتحدة",
          purchasedOutsideCountry: "يرجى تقديم معلومات الشراء خارج الدولة",
          purchasedOutsideCurrency: "يرجى تقديم العملة المستخدمة خارج الدولة",
          anyMedicinesTaken: "يرجى تقديم الأدوية التي تم تناولها",
          medicineCoveredByOtherInsurance: "يرجى تقديم الأدوية المغطاة بتأمين آخر",
          otherCoverage: "يرجى تقديم تغطية أخرى",
          nameOfInsuranceCompany: "يرجى تقديم اسم شركة التأمين",
          insuranceId: "يرجى تقديم رقم التأمين",
          memberSignature: "يرجى تقديم توقيع العضو",
          numberOfPrescriptions: "يرجى تقديم عدد الوصفات الطبية",
          prescribingPhysicianNpiNumber: "يرجى تقديم رقم NPI للطبيب المعالج",
          prescribingPhysicianPhoneNumber: "يرجى تقديم رقم هاتف الطبيب المعالج",
          prescribingPhysicianName: "يرجى تقديم اسم الطبيب المعالج",
          prescribingPhysicianAddress: "يرجى تقديم عنوان الطبيب المعالج",
          prescribingPhysicianCityStateZip: "يرجى تقديم مدينة/ولاية/رمز بريدي الطبيب المعالج",
          prescribingPhysicianAdditionalComments: "يرجى تقديم تعليقات إضافية للطبيب المعالج",
          grandTotal: "يرجى تقديم الإجمالي الكلي",
          otherInformation: "يرجى تقديم معلومات أخرى"
        },
        send: {
          subject: "يرجى تقديم الموضوع",
          content: "يرجى تقديم المحتوى"
        },
        allergy: {
          dateOfAllergy: "يرجى تقديم تاريخ الحساسية",
          numberOfVialsAllergy: "يرجى تقديم عدد قوارير الحساسية",
          numberOfTreatmentsAllergy: "يرجى تقديم عدد علاجات الحساسية",
          daysSupplyAllergy: "يرجى تقديم مدة إمداد الحساسية",
          vialContainsAllergy: "يرجى تقديم محتوى القارورة للحساسية",
          administeredByAllergy: "يرجى تقديم اسم المسؤول عن إعطاء الحساسية",
          directionsAllergy: "يرجى تقديم تعليمات الحساسية",
          ingredientsAllergy: "يرجى تقديم مكونات الحساسية",
          chargePerTreatmentAllergy: "يرجى تقديم تكلفة كل علاج للحساسية",
          chargeForPreparationAllergy: "يرجى تقديم تكلفة التحضير للحساسية",
          totalChargeAllergy: "يرجى تقديم إجمالي تكلفة الحساسية"
        }
      },
      settled: {
        missingReject: {
          reason: "يرجى تقديم سبب الرفض"
        },
        payClaim: {
          bankAccount: "يرجى تقديم رقم الحساب المصرفي",
          payingAmount: "يرجى تقديم مبلغ الدفع"
        },
        return: {
          reason: "يرجى تقديم سبب الإرجاع"
        }
      }
    },
    managePrescription: {
      prescription: {
        ndcAdd: {
          ndcNumber: "يرجى تقديم رقم NDC",
          selectedNDC: "يرجى تقديم NDC المحدد"
        },
        invoice: {
          claimType: "يرجى تقديم نوع المطالبة",
          appointmentId: "يرجى تقديم معرف الموعد",
          patientInsurance: "يرجى تقديم تأمين المريض",
          invoiceDate: "يرجى تقديم تاريخ الفاتورة",
          medicationStartDate: "يرجى تقديم تاريخ بدء الدواء",
          appointmentDate: "يرجى تقديم تاريخ الموعد",
          grandTotal: "يرجى تقديم الإجمالي الكلي",
          coPay: "يرجى تقديم المبلغ المشترك (Co-Pay)",
          patientPay: "يرجى تقديم مبلغ المريض",
          insurancePay: "يرجى تقديم مبلغ التأمين",
          otherInformation: "يرجى تقديم معلومات أخرى",
          medicineType: "يرجى تقديم نوع الدواء",
          frequency: "يرجى تقديم التكرار",
          foodRequirementType: "يرجى تقديم نوع متطلبات الطعام",
          durationType: "يرجى تقديم نوع المدة",
          durationNumber: "يرجى تقديم عدد الأيام/المدة",
          startDate: "يرجى تقديم تاريخ البدء",
          dosage: "يرجى تقديم الجرعة",
          isRefill: "يرجى تقديم ما إذا كان هناك إعادة تعبئة",
          instructions: "يرجى تقديم التعليمات",
          notes: "يرجى تقديم الملاحظات",
          price: "يرجى تقديم السعر",
          quantity: "يرجى تقديم الكمية",
          tax: "يرجى تقديم الضريبة",
          total: "يرجى تقديم الإجمالي"
        }
      }
    }
  },
};
