import { useMemo } from "react";
import { Box, Card } from "@mantine/core";
import { Breadcrumb } from "../../../includes/BreadCrumbs";
import { PageTopBarAndFilter } from "../../../common/PageTopBarAndFilter";
import { PagePagination } from "../../../common/PagePagination";
import type { RootState } from "../../../../redux/store";
import { useSelector } from "react-redux";
import { PrescriptionList } from "./sections/list/PrescriptionList";

export const Prescription = () => {
  // const loaderData = useLoaderData();
  const filterState = useSelector((state: RootState) => state.pageTopBarAndFilter);
  const prescriptionData = [
    {
      id: 1,
      snahId: "SNAH12345",
      patientName: "John William",
      physicianName: "John Dow",
      date: "2025-06-10",
      status: "Pending",
      type: "Pickup",
    },
    {
      id: 2,
      snahId: "SNAH12346",
      patientName: "Emily Clark",
      physicianName: "Sarah Lee",
      date: "2025-06-11",
      status: "Initiate",
      type: "Pickup",
    },
    {
      id: 3,
      snahId: "SNAH12347",
      patientName: "Michael Brown",
      physicianName: "David Kim",
      date: "2025-06-12",
      status: "Processing",
      type: "Pickup",
    },
    {
      id: 4,
      snahId: "SNAH12348",
      patientName: "Sophia Turner",
      physicianName: "Olivia Smith",
      date: "2025-06-13",
      status: "Picked Up",
      type: "Pickup",
    },
    {
      id: 5,
      snahId: "SNAH12349",
      patientName: "Liam Johnson",
      physicianName: "William Jones",
      date: "2025-06-14",
      status: "Rejected",
      type: "Pickup",
    },
    {
      id: 170,
      snahId: "SNAH12361",
      patientName: "Benjamin Carter",
      physicianName: "Andrew Roberts",
      date: "2025-06-26",
      status: "Delivered",
      type: "Pickup",
    },
    {
      id: 6,
      snahId: "SNAH12350",
      patientName: "Olivia Martin",
      physicianName: "James Wilson",
      date: "2025-06-15",
      status: "Pending",
      type: "Delivery",
    },
    {
      id: 7,
      snahId: "SNAH12351",
      patientName: "Noah White",
      physicianName: "Benjamin Moore",
      date: "2025-06-16",
      status: "Initiate",
      type: "Delivery",
    },
    {
      id: 8,
      snahId: "SNAH12352",
      patientName: "Emma Harris",
      physicianName: "Lucas Taylor",
      date: "2025-06-17",
      status: "Processing",
      type: "Delivery",
    },
    {
      id: 10,
      snahId: "SNAH12354",
      patientName: "Ava Walker",
      physicianName: "Jack Thomas",
      date: "2025-06-19",
      status: "Locating Driver",
      type: "Delivery",
    },
    {
      id: 11,
      snahId: "SNAH12355",
      patientName: "Elijah Hall",
      physicianName: "Alexander Scott",
      date: "2025-06-20",
      status: "Picked Up By Driver",
      type: "Delivery",
    },
    {
      id: 12,
      snahId: "SNAH12356",
      patientName: "Charlotte Young",
      physicianName: "Daniel King",
      date: "2025-06-21",
      status: "Out For Delivery",
      type: "Delivery",
    },
    {
      id: 13,
      snahId: "SNAH12357",
      patientName: "William Allen",
      physicianName: "Matthew Wright",
      date: "2025-06-22",
      status: "Delivered",
      type: "Delivery",
    },
    {
      id: 14,
      snahId: "SNAH12358",
      patientName: "Amelia King",
      physicianName: "Joseph Lopez",
      date: "2025-06-23",
      status: "Rejected",
      type: "Delivery",
    },
    {
      id: 15,
      snahId: "SNAH12359",
      patientName: "James Hill",
      physicianName: "Samuel Gonzalez",
      date: "2025-06-24",
      status: "Initiate",
      type: "Pickup",
    },
    {
      id: 16,
      snahId: "SNAH12360",
      patientName: "Mia Nelson",
      physicianName: "David Perez",
      date: "2025-06-25",
      status: "Pending",
      type: "Delivery",
    },
    {
      id: 17,
      snahId: "SNAH12361",
      patientName: "Benjamin Carter",
      physicianName: "Andrew Roberts",
      date: "2025-06-26",
      status: "Delivered",
      type: "Pickup",
    },
    {
      id: 18,
      snahId: "SNAH12362",
      patientName: "Harper Mitchell",
      physicianName: "Joshua Evans",
      date: "2025-06-27",
      status: "Rejected",
      type: "Delivery",
    },
    {
      id: 19,
      snahId: "SNAH12363",
      patientName: "Lucas Martinez",
      physicianName: "Ryan Edwards",
      date: "2025-06-28",
      status: "Processing",
      type: "Pickup",
    },
    {
      id: 20,
      snahId: "SNAH12364",
      patientName: "Evelyn Clark",
      physicianName: "Christopher Collins",
      date: "2025-06-29",
      status: "Initiate",
      type: "Delivery",
    },
    {
      id: 21,
      snahId: "SNAH12365",
      patientName: "Henry Turner",
      physicianName: "Nathan Stewart",
      date: "2025-06-30",
      status: "Pending",
      type: "Pickup",
    },
    {
      id: 22,
      snahId: "SNAH12366",
      patientName: "Abigail Lewis",
      physicianName: "Christian Morris",
      date: "2025-07-01",
      status: "Delivered",
      type: "Delivery",
    },
    {
      id: 23,
      snahId: "SNAH12367",
      patientName: "Jack Walker",
      physicianName: "Jonathan Rogers",
      date: "2025-07-02",
      status: "Rejected",
      type: "Pickup",
    },
    {
      id: 24,
      snahId: "SNAH12368",
      patientName: "Ella Harris",
      physicianName: "Brandon Reed",
      date: "2025-07-03",
      status: "Processing",
      type: "Delivery",
    },
    {
      id: 25,
      snahId: "SNAH12369",
      patientName: "Alexander Young",
      physicianName: "Aaron Cook",
      date: "2025-07-04",
      status: "Initiate",
      type: "Pickup",
    },
    {
      id: 26,
      snahId: "SNAH12370",
      patientName: "Scarlett Allen",
      physicianName: "Adam Bailey",
      date: "2025-07-05",
      status: "Pending",
      type: "Delivery",
    },
    {
      id: 27,
      snahId: "SNAH12371",
      patientName: "Logan King",
      physicianName: "Austin Rivera",
      date: "2025-07-06",
      status: "Delivered",
      type: "Pickup",
    },
    {
      id: 28,
      snahId: "SNAH12372",
      patientName: "Grace Hill",
      physicianName: "Dylan Cooper",
      date: "2025-07-07",
      status: "Rejected",
      type: "Delivery",
    },
    {
      id: 29,
      snahId: "SNAH12373",
      patientName: "Sebastian Nelson",
      physicianName: "Ethan Ward",
      date: "2025-07-08",
      status: "Processing",
      type: "Pickup",
    },
    {
      id: 30,
      snahId: "SNAH12374",
      patientName: "Chloe Carter",
      physicianName: "Gabriel Torres",
      date: "2025-07-09",
      status: "Initiate",
      type: "Delivery",
    },
    {
      id: 31,
      snahId: "SNAH12375",
      patientName: "Daniel Mitchell",
      physicianName: "Isaac Peterson",
      date: "2025-07-10",
      status: "Pending",
      type: "Pickup",
    },
    {
      id: 32,
      snahId: "SNAH12376",
      patientName: "Victoria Martinez",
      physicianName: "Julian Gray",
      date: "2025-07-11",
      status: "Delivered",
      type: "Delivery",
    },
    {
      id: 33,
      snahId: "SNAH12377",
      patientName: "Matthew Clark",
      physicianName: "Levi Ramirez",
      date: "2025-07-12",
      status: "Rejected",
      type: "Pickup",
    },
    {
      id: 34,
      snahId: "SNAH12378",
      patientName: "Penelope Turner",
      physicianName: "Lincoln James",
      date: "2025-07-13",
      status: "Processing",
      type: "Delivery",
    },
    {
      id: 35,
      snahId: "SNAH12379",
      patientName: "Jackson Johnson",
      physicianName: "Luke Watson",
      date: "2025-07-14",
      status: "Initiate",
      type: "Pickup",
    },
    {
      id: 36,
      snahId: "SNAH12380",
      patientName: "Layla Martin",
      physicianName: "Mason Brooks",
      date: "2025-07-15",
      status: "Pending",
      type: "Delivery",
    },
    {
      id: 37,
      snahId: "SNAH12381",
      patientName: "Aiden White",
      physicianName: "Michael Kelly",
      date: "2025-07-16",
      status: "Delivered",
      type: "Pickup",
    },
    {
      id: 38,
      snahId: "SNAH12382",
      patientName: "Zoe Harris",
      physicianName: "Nathaniel Price",
      date: "2025-07-17",
      status: "Rejected",
      type: "Delivery",
    },
    {
      id: 39,
      snahId: "SNAH12383",
      patientName: "Samuel Lewis",
      physicianName: "Owen Bennett",
      date: "2025-07-18",
      status: "Processing",
      type: "Pickup",
    },
    {
      id: 40,
      snahId: "SNAH12384",
      patientName: "Hannah Walker",
      physicianName: "Parker Wood",
      date: "2025-07-19",
      status: "Initiate",
      type: "Delivery",
    },
    {
      id: 41,
      snahId: "SNAH12385",
      patientName: "Carter Hall",
      physicianName: "Ryan Barnes",
      date: "2025-07-20",
      status: "Pending",
      type: "Pickup",
    },
    {
      id: 42,
      snahId: "SNAH12386",
      patientName: "Lily Young",
      physicianName: "Sebastian Ross",
      date: "2025-07-21",
      status: "Delivered",
      type: "Delivery",
    },
    {
      id: 43,
      snahId: "SNAH12387",
      patientName: "Wyatt Allen",
      physicianName: "Theodore Henderson",
      date: "2025-07-22",
      status: "Rejected",
      type: "Pickup",
    },
    {
      id: 44,
      snahId: "SNAH12388",
      patientName: "Sofia King",
      physicianName: "Thomas Coleman",
      date: "2025-07-23",
      status: "Processing",
      type: "Delivery",
    },
    {
      id: 45,
      snahId: "SNAH12389",
      patientName: "Julian Hill",
      physicianName: "William Jenkins",
      date: "2025-07-24",
      status: "Initiate",
      type: "Pickup",
    },
    {
      id: 46,
      snahId: "SNAH12390",
      patientName: "Aria Nelson",
      physicianName: "Zachary Perry",
      date: "2025-07-25",
      status: "Pending",
      type: "Delivery",
    },
    {
      id: 47,
      snahId: "SNAH12391",
      patientName: "Grayson Carter",
      physicianName: "Anthony Powell",
      date: "2025-07-26",
      status: "Delivered",
      type: "Pickup",
    },
    {
      id: 48,
      snahId: "SNAH12392",
      patientName: "Avery Mitchell",
      physicianName: "Charles Long",
      date: "2025-07-27",
      status: "Rejected",
      type: "Delivery",
    },
    {
      id: 49,
      snahId: "SNAH12393",
      patientName: "Leah Martinez",
      physicianName: "Dominic Patterson",
      date: "2025-07-28",
      status: "Processing",
      type: "Pickup",
    },
    {
      id: 50,
      snahId: "SNAH12394",
      patientName: "Luke Clark",
      physicianName: "Eli Hughes",
      date: "2025-07-29",
      status: "Initiate",
      type: "Delivery",
    },
    {
      id: 51,
      snahId: "SNAH12395",
      patientName: "Mila Turner",
      physicianName: "Hunter Flores",
      date: "2025-07-30",
      status: "Pending",
      type: "Pickup",
    },
  ];

  const prescriptionList = useMemo(() => {
    let rows = [...prescriptionData];
    const role = (filterState.filter.statusFilter || "all").toLowerCase();
    if (role !== "all") rows = rows.filter(r => r.status.toLowerCase() === role);
    return rows;
  }, [prescriptionData, filterState.filter.statusFilter]);

  const topBarAndFilter = {
    type: "claim",
    title: "Claim",
    heading: "List of all prescription you can find below",
    viewMode: "grid",
    whatNeeded: {
      isViewModeNeeded: true,
      isFilterNeeded: true,
    },
  };

  return (
    <Box>
      <Box>
        <Breadcrumb
          dataPass={{
            pageTitle: "Prescription List",
            items: [
              { title: "Manage Prescription", href: "#" },
              { title: "Prescription List", href: "#", isActive: true },
            ],
          }}
        />
      </Box>
      <Box>
        <Card
          withBorder
          shadow="sm"
          className="rounded-xl bg-white/80 dark:bg-slate-900/60 backdrop-blur-xl border-t border-slate-200/60 dark:border-slate-700/60"
        >
          <PageTopBarAndFilter dataPass={{ topBarAndFilter }} />
          <PrescriptionList dataPass={{ prescriptionList }} />
          <PagePagination dataPass={{ total: prescriptionList.length || 0 }} />
        </Card>
      </Box>
    </Box>
  );
};
